version: "3.8"

services:
  #nginx-container
  nginx-example3:
    container_name: nginx-example3
    image: nginx:latest
  #nginx-container2
  nginx-example4:
    container_name: nginx-example4
    image: nginx:latest
  #node-container
  node-example:
    container_name: node-example
    image: node:14-alpine
