version: "3.8"

services:
  mysql-example:
    container_name: mysql-example
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
      MYSQL_USER: root
    volumes:
      - mysql-data3:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - backend-network

  phpmyadmin-example:
    container_name: phpmyadmin-example
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql-example
      PMA_PASSWORD: root
      PMA_USER: root
      PMA_PORT: 3306
    ports:
      - "8080:80"
    networks:
      - backend-network
    depends_on:
      - mysql-example
    restart: always

networks:
  backend-network:
    name: backend-network

volumes:
  mysql-data3:
    name: mysql-data3
